name: Deploy to Github Pages

# run when a commit is pushed to "source" branch
on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    # Checkout with full git history (required for .GitInfo and accurate lastmod)
    - uses: actions/checkout@v4
      with:
        fetch-depth: 0  # Fetch entire git history (mandatory for SEO/lastmod)

    # Cache Hugo resources to improve build speed
    - name: Cache Hugo resources
      uses: actions/cache@v3
      with:
        path: |
          ~/.cache/hugo
          resources/_gen
        key: ${{ runner.os }}-hugo-${{ hashFiles('**/hugo.yaml') }}
    
    # Cache Node.js modules to speed up npm install
    - name: Cache node modules
      uses: actions/cache@v3
      with:
        path: ~/.npm
        key: ${{ runner.os }}-node-${{ hashFiles('**/package-lock.json') }}

    # Hugo Install
    - name: Setup Hugo
      uses: peaceiris/actions-hugo@v3
      with:
        hugo-version: 'latest'
        extended: true

    # Update Hugo modules and tidy up dependencies
    - name: Update Hugo Modules
      run: hugo mod tidy

    # Setup Node.js for using npm modules required by Hugo
    - name: Setup Node
      uses: actions/setup-node@v4
      with:
        node-version: 20

    # Install npm modules (using cached data if available)
    - name: Install node modules
      run: |
        hugo mod npm pack
        npm install       

    # Build Hugo site with minification
    - name: Build
      run: hugo --minify --ignoreCache

    # push the generated content into the `gh-pages` branch.
    - name: Deploy
      uses: peaceiris/actions-gh-pages@v4
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_branch: gh-pages
        publish_dir: ./public